name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install ruff
      - name: Lint (ruff)
        run: |
          ruff check backend || true
      - name: Run tests (pytest)
        run: |
          pytest -q
        working-directory: backend

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install deps
        run: npm ci
        working-directory: frontend
      - name: Lint
        run: npm run lint --silent || true
        working-directory: frontend
      - name: Build
        run: npm run build --silent
        working-directory: frontend
      - name: Test
        run: npm test --silent
        working-directory: frontend


